!/************************/
!/*    hdf5utils.F90     */
!/*    VERSION 1.0       */
!/*     2022/09/07       */
!/*  © MARCO AZIMONTI    */
!/************************/

MODULE HDF5UTILS
    IMPLICIT NONE

PRIVATE :: FILE_ID_F
PUBLIC  :: READ_I4, READ_I8, READ_R8, READ_VR8
PUBLIC  :: WRITE_I4, WRITE_I8, WRITE_R8, WRITE_VR8, WRITE_MR8

CONTAINS

    SUBROUTINE READ_I4(FILENAME, DATASETNAME, I)
        !DEC$ ATTRIBUTES DLLEXPORT :: READ_I4
        USE HDF5
        CHARACTER(LEN=128), INTENT(IN)         :: FILENAME, DATASETNAME
        INTEGER, INTENT(OUT)                   :: I
        INTEGER(HID_T) :: FILE_ID, DATASET_ID, DATASPACE_ID
        INTEGER(HSIZE_T), DIMENSION(1:1)       :: DIMS, MAXDIMS
        INTEGER                                :: ERROR

        CALL H5OPEN_F(ERROR)
        CALL H5FOPEN_F(FILENAME, H5F_ACC_RDONLY_F, FILE_ID, ERROR)
        CALL H5DOPEN_F(FILE_ID, DATASETNAME, DATASET_ID, ERROR)
        CALL H5DGET_SPACE_F(DATASET_ID, DATASPACE_ID, ERROR)
        CALL H5SGET_SIMPLE_EXTENT_DIMS_F(DATASPACE_ID, DIMS, MAXDIMS, ERROR)
        CALL H5DREAD_F(DATASET_ID, H5T_NATIVE_INTEGER, I, DIMS, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)
        CALL H5FCLOSE_F(FILE_ID, ERROR)
    END SUBROUTINE READ_I4


    SUBROUTINE READ_I8(FILENAME, DATASETNAME, I)
        !DEC$ ATTRIBUTES DLLEXPORT :: READ_I8
        USE HDF5
        CHARACTER(LEN=128), INTENT(IN)         :: FILENAME, DATASETNAME
        INTEGER(KIND=8), INTENT(OUT)           :: I
        INTEGER(HID_T) :: FILE_ID, DATASET_ID, DATASPACE_ID
        INTEGER(HSIZE_T), DIMENSION(1:1)       :: DIMS, MAXDIMS
        INTEGER                                :: ERROR

        CALL H5OPEN_F(ERROR)
        CALL H5FOPEN_F(FILENAME, H5F_ACC_RDONLY_F, FILE_ID, ERROR)
        CALL H5DOPEN_F(FILE_ID, DATASETNAME, DATASET_ID, ERROR)
        CALL H5DGET_SPACE_F(DATASET_ID, DATASPACE_ID, ERROR)
        CALL H5SGET_SIMPLE_EXTENT_DIMS_F(DATASPACE_ID, DIMS, MAXDIMS, ERROR)
        CALL H5DREAD_F(DATASET_ID, H5T_STD_I64LE, I, DIMS, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)
        CALL H5FCLOSE_F(FILE_ID, ERROR)
    END SUBROUTINE READ_I8


    SUBROUTINE READ_R8(FILENAME, DATASETNAME, R)
        !DEC$ ATTRIBUTES DLLEXPORT :: READ_R8
        USE HDF5
        INTEGER, PARAMETER                     :: KINDR = KIND(0D0)
        CHARACTER(LEN=128), INTENT(IN)         :: FILENAME, DATASETNAME
        REAL(KINDR), INTENT(OUT)               :: R
        INTEGER(HID_T) :: FILE_ID, DATASET_ID, DATASPACE_ID
        INTEGER(HSIZE_T), DIMENSION(1:1)       :: DIMS, MAXDIMS
        INTEGER                                :: ERROR

        CALL H5OPEN_F(ERROR)
        CALL H5FOPEN_F(FILENAME, H5F_ACC_RDONLY_F, FILE_ID, ERROR)
        CALL H5DOPEN_F(FILE_ID, DATASETNAME, DATASET_ID, ERROR)
        CALL H5DGET_SPACE_F(DATASET_ID, DATASPACE_ID, ERROR)
        CALL H5SGET_SIMPLE_EXTENT_DIMS_F(DATASPACE_ID, DIMS, MAXDIMS, ERROR)
        CALL H5DREAD_F(DATASET_ID, H5T_NATIVE_DOUBLE, R, DIMS, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)
        CALL H5FCLOSE_F(FILE_ID, ERROR)
    END SUBROUTINE READ_R8


    SUBROUTINE READ_VR8(FILENAME, DATASETNAME, VV)
        !DEC$ ATTRIBUTES DLLEXPORT :: READ_VR8
        USE HDF5
        INTEGER, PARAMETER                     :: KINDR = KIND(0D0)
        CHARACTER(LEN=128), INTENT(IN)         :: FILENAME, DATASETNAME
        REAL(KINDR),ALLOCATABLE, DIMENSION(:), INTENT(OUT)  :: VV
        INTEGER(HID_T) :: FILE_ID, DATASET_ID, DATASPACE_ID 
        INTEGER(HSIZE_T), DIMENSION(1:1)            :: DIMS, MAXDIMS
        INTEGER                                :: ERROR

        CALL H5OPEN_F(ERROR)
        CALL H5FOPEN_F(FILENAME, H5F_ACC_RDONLY_F, FILE_ID, ERROR)
        CALL H5DOPEN_F(FILE_ID, DATASETNAME, DATASET_ID, ERROR)
        CALL H5DGET_SPACE_F(DATASET_ID, DATASPACE_ID, ERROR)
        CALL H5SGET_SIMPLE_EXTENT_DIMS_F(DATASPACE_ID, DIMS, MAXDIMS, ERROR)
        ALLOCATE(VV(1:DIMS(1)))
        CALL H5DREAD_F(DATASET_ID, H5T_NATIVE_DOUBLE, VV, DIMS, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)
        CALL H5FCLOSE_F(FILE_ID, ERROR)

    END SUBROUTINE READ_VR8

    SUBROUTINE WRITE_I4(FILENAME, GROUPNAME, DATASETNAME, I)
        !DEC$ ATTRIBUTES DLLEXPORT :: WRITE_I4
        USE HDF5
        INTEGER, PARAMETER                     :: MAXDIMS = 1
        INTEGER(HSIZE_T), DIMENSION(1:MAXDIMS) :: DIMS ! DIMENSIONS OF DATA
        INTEGER(HSIZE_T), DIMENSION(1:MAXDIMS) :: CDIMS ! SIZES OF CHUNKED DATA
        CHARACTER(LEN=128), INTENT(IN)         :: FILENAME, GROUPNAME, DATASETNAME
        CHARACTER(LEN=257)                     :: DATASETNAMEFULL
        INTEGER,         INTENT(IN)            :: I
        INTEGER(HID_T)                         :: FILE_ID, GROUP_ID, DATASET_ID, &
     &  DATASPACE_ID, PLIST_ID
        INTEGER                                :: ERROR
        LOGICAL                                :: EXISTS

        CALL H5OPEN_F(ERROR)
        FILE_ID = FILE_ID_F(FILENAME)
        CALL H5LEXISTS_F(FILE_ID, GROUPNAME, EXISTS, ERROR)
        IF(.NOT.EXISTS) THEN
            CALL H5GCREATE_F(FILE_ID, GROUPNAME, GROUP_ID, ERROR)
        END IF
        DATASETNAMEFULL = TRIM(GROUPNAME) // "/" // TRIM(DATASETNAME)
        ! DELETE THE OLD DATASET IF EXISTS
        CALL H5LEXISTS_F(FILE_ID, DATASETNAMEFULL, EXISTS, ERROR)
        IF(EXISTS) THEN
            CALL H5LDELETE_F(FILE_ID, DATASETNAMEFULL, ERROR)
        END IF

        DIMS(1:1) = 1
        CALL H5SCREATE_SIMPLE_F(MAXDIMS, DIMS, DATASPACE_ID, ERROR)
        CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PLIST_ID, ERROR)
        ! DATASET MUST BE CHUNKED FOR COMPRESSION
        CDIMS(1:1) = 1
        CALL H5PSET_CHUNK_F(PLIST_ID, 1, CDIMS, ERROR)
        ! SET COMPRESSION
        CALL H5PSET_DEFLATE_F(PLIST_ID, 9, ERROR)
        ! CREATE DATA SET
        CALL H5DCREATE_F(FILE_ID, DATASETNAMEFULL, H5T_NATIVE_INTEGER, DATASPACE_ID, &
     &  DATASET_ID, ERROR, DCPL_ID=PLIST_ID)

        ! WRITE THE DATA
        CALL H5DWRITE_F(DATASET_ID, H5T_NATIVE_INTEGER, I, DIMS, ERROR)

        CALL H5SCLOSE_F(DATASPACE_ID, ERROR)
        CALL H5PCLOSE_F(PLIST_ID, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)
        CALL H5FCLOSE_F(FILE_ID, ERROR)
    END SUBROUTINE WRITE_I4


    SUBROUTINE WRITE_I8(FILENAME, GROUPNAME, DATASETNAME, I)
        !DEC$ ATTRIBUTES DLLEXPORT :: WRITE_I8
        USE HDF5
        INTEGER, PARAMETER                     :: MAXDIMS = 1
        INTEGER(HSIZE_T), DIMENSION(1:MAXDIMS) :: DIMS ! DIMENSIONS OF DATA
        INTEGER(HSIZE_T), DIMENSION(1:MAXDIMS) :: CDIMS ! SIZES OF CHUNKED DATA
        CHARACTER(LEN=128), INTENT(IN)         :: FILENAME, GROUPNAME, DATASETNAME
        CHARACTER(LEN=257)                     :: DATASETNAMEFULL
        INTEGER(KIND=8), INTENT(IN)            :: I
        INTEGER(HID_T)                         :: FILE_ID, GROUP_ID, DATASET_ID, &
     &  DATASPACE_ID, PLIST_ID
        INTEGER                                :: ERROR
        LOGICAL                                :: EXISTS

        CALL H5OPEN_F(ERROR)
        FILE_ID = FILE_ID_F(FILENAME)
        CALL H5LEXISTS_F(FILE_ID, GROUPNAME, EXISTS, ERROR)
        IF(.NOT.EXISTS) THEN
            CALL H5GCREATE_F(FILE_ID, GROUPNAME, GROUP_ID, ERROR)
        END IF
        DATASETNAMEFULL = TRIM(GROUPNAME) // "/" // TRIM(DATASETNAME)
        ! DELETE THE OLD DATASET IF EXISTS
        CALL H5LEXISTS_F(FILE_ID, DATASETNAMEFULL, EXISTS, ERROR)
        IF(EXISTS) THEN
            CALL H5LDELETE_F(FILE_ID, DATASETNAMEFULL, ERROR)
        END IF

        DIMS(1:1) = 1
        CALL H5SCREATE_SIMPLE_F(MAXDIMS, DIMS, DATASPACE_ID, ERROR)
        CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PLIST_ID, ERROR)
        ! DATASET MUST BE CHUNKED FOR COMPRESSION
        CDIMS(1:1) = 1
        CALL H5PSET_CHUNK_F(PLIST_ID, 1, CDIMS, ERROR)
        ! SET COMPRESSION
        CALL H5PSET_DEFLATE_F(PLIST_ID, 9, ERROR)
        ! CREATE DATA SET
        CALL H5DCREATE_F(FILE_ID, DATASETNAMEFULL, H5T_STD_I64LE, DATASPACE_ID, &
     &  DATASET_ID, ERROR, DCPL_ID=PLIST_ID)

        ! WRITE THE DATA
        CALL H5DWRITE_F(DATASET_ID, H5T_STD_I64LE, I, DIMS, ERROR)

        CALL H5SCLOSE_F(DATASPACE_ID, ERROR)
        CALL H5PCLOSE_F(PLIST_ID, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)
        CALL H5FCLOSE_F(FILE_ID, ERROR)
    END SUBROUTINE WRITE_I8


    SUBROUTINE WRITE_R8(FILENAME, GROUPNAME, DATASETNAME, R)
        !DEC$ ATTRIBUTES DLLEXPORT :: WRITE_R8
        USE HDF5
        INTEGER, PARAMETER                     :: KINDR = KIND(0D0), MAXDIMS = 1
        INTEGER(HSIZE_T), DIMENSION(1:MAXDIMS) :: DIMS ! DIMENSIONS OF DATA
        INTEGER(HSIZE_T), DIMENSION(1:MAXDIMS) :: CDIMS ! SIZES OF CHUNKED DATA
        CHARACTER(LEN=128), INTENT(IN)         :: FILENAME, GROUPNAME, DATASETNAME
        CHARACTER(LEN=257)                     :: DATASETNAMEFULL
        REAL(KINDR), INTENT(IN)                :: R
        INTEGER(HID_T)                         :: FILE_ID, GROUP_ID, DATASET_ID, &
     &  DATASPACE_ID, PLIST_ID
        INTEGER                                :: ERROR
        LOGICAL                                :: EXISTS

        CALL H5OPEN_F(ERROR)
        FILE_ID = FILE_ID_F(FILENAME)
        CALL H5LEXISTS_F(FILE_ID, GROUPNAME, EXISTS, ERROR)
        IF(.NOT.EXISTS) THEN
            CALL H5GCREATE_F(FILE_ID, GROUPNAME, GROUP_ID, ERROR)
        END IF
        DATASETNAMEFULL = TRIM(GROUPNAME) // "/" // TRIM(DATASETNAME)
        ! DELETE THE OLD DATASET IF EXISTS
        CALL H5LEXISTS_F(FILE_ID, DATASETNAMEFULL, EXISTS, ERROR)
        IF(EXISTS) THEN
            CALL H5LDELETE_F(FILE_ID, DATASETNAMEFULL, ERROR)
        END IF

        DIMS(1:1) = 1
        CALL H5SCREATE_SIMPLE_F(MAXDIMS, DIMS, DATASPACE_ID, ERROR)
        CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PLIST_ID, ERROR)
        ! DATASET MUST BE CHUNKED FOR COMPRESSION
        CDIMS(1:1) = 1
        CALL H5PSET_CHUNK_F(PLIST_ID, 1, CDIMS, ERROR)
        ! SET COMPRESSION
        CALL H5PSET_DEFLATE_F(PLIST_ID, 9, ERROR)
        ! CREATE DATA SET
        CALL H5DCREATE_F(FILE_ID, DATASETNAMEFULL, H5T_NATIVE_DOUBLE, DATASPACE_ID, &
     &  DATASET_ID, ERROR, DCPL_ID=PLIST_ID)

        ! WRITE THE DATA
        CALL H5DWRITE_F(DATASET_ID, H5T_NATIVE_DOUBLE, R, DIMS, ERROR)

        CALL H5SCLOSE_F(DATASPACE_ID, ERROR)
        CALL H5PCLOSE_F(PLIST_ID, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)
        CALL H5FCLOSE_F(FILE_ID, ERROR)
    END SUBROUTINE WRITE_R8

    SUBROUTINE WRITE_VR8(FILENAME, GROUPNAME, DATASETNAME, VV)
        !DEC$ ATTRIBUTES DLLEXPORT :: WRITE_VR8
        USE HDF5
        INTEGER, PARAMETER                     :: KINDR = KIND(0D0), MAXDIMS = 1
        INTEGER(HSIZE_T), DIMENSION(1:MAXDIMS) :: DIMS ! DIMENSIONS OF DATA
        INTEGER(HSIZE_T), DIMENSION(1:MAXDIMS) :: CDIMS ! SIZES OF CHUNKED DATA
        CHARACTER(LEN=128), INTENT(IN)         :: FILENAME, GROUPNAME, DATASETNAME
        CHARACTER(LEN=257)                     :: DATASETNAMEFULL
        REAL(KINDR), DIMENSION(:), INTENT(IN)  :: VV
        INTEGER(HID_T)                         :: FILE_ID, GROUP_ID, DATASET_ID, &
     &  DATASPACE_ID, PLIST_ID
        INTEGER                                :: ERROR
        LOGICAL                                :: EXISTS

        CALL H5OPEN_F(ERROR)
        FILE_ID = FILE_ID_F(FILENAME)
        CALL H5LEXISTS_F(FILE_ID, GROUPNAME, EXISTS, ERROR)
        IF(.NOT.EXISTS) THEN
            CALL H5GCREATE_F(FILE_ID, GROUPNAME, GROUP_ID, ERROR)
        END IF
        DATASETNAMEFULL = TRIM(GROUPNAME) // "/" // TRIM(DATASETNAME)
        ! DELETE THE OLD DATASET IF EXISTS
        CALL H5LEXISTS_F(FILE_ID, DATASETNAMEFULL, EXISTS, ERROR)
        IF(EXISTS) THEN
            CALL H5LDELETE_F(FILE_ID, DATASETNAMEFULL, ERROR)
        END IF

        DIMS(1:1) = (UBOUND(VV))
        CALL H5SCREATE_SIMPLE_F(MAXDIMS, DIMS, DATASPACE_ID, ERROR)
        CALL H5PCREATE_F(H5P_DATASET_CREATE_F, PLIST_ID, ERROR)
        ! DATASET MUST BE CHUNKED FOR COMPRESSION
        CDIMS(1:1) = MIN(UBOUND(VV), 5)
        CALL H5PSET_CHUNK_F(PLIST_ID, 1, CDIMS, ERROR)
        ! SET COMPRESSION
        CALL H5PSET_DEFLATE_F(PLIST_ID, 9, ERROR)
        ! CREATE DATA SET
        CALL H5DCREATE_F(FILE_ID, DATASETNAMEFULL, H5T_NATIVE_DOUBLE, DATASPACE_ID, &
     &  DATASET_ID, ERROR, DCPL_ID=PLIST_ID)

        ! WRITE THE DATA
        CALL H5DWRITE_F(DATASET_ID, H5T_NATIVE_DOUBLE, VV, DIMS, ERROR)

        CALL H5SCLOSE_F(DATASPACE_ID, ERROR)
        CALL H5PCLOSE_F(PLIST_ID, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)
        CALL H5FCLOSE_F(FILE_ID, ERROR)
    END SUBROUTINE WRITE_VR8


    SUBROUTINE WRITE_MR8(FILENAME, GROUPNAME, DATASETNAME, MM)
        !DEC$ ATTRIBUTES DLLEXPORT :: WRITE_MR8
        INTEGER, PARAMETER                      :: KINDR = KIND(0D0)
        CHARACTER(LEN=128), INTENT(IN)          :: FILENAME, GROUPNAME, DATASETNAME
        REAL(KINDR), DIMENSION(:,:), INTENT(IN) :: MM
        REAL(KINDR), DIMENSION(UBOUND(MM,1) * UBOUND(MM,2)) :: VV
        INTEGER                                 :: I

        DO I = 1, UBOUND(MM,2)
            VV(1 + (I-1)* UBOUND(MM,2) : UBOUND(MM,1) + (I-1) * UBOUND(MM,2)) &
     &      = MM(:,I)
        END DO
        CALL WRITE_VR8(FILENAME, GROUPNAME, DATASETNAME, VV)
    END SUBROUTINE WRITE_MR8


    FUNCTION FILE_ID_F(FILENAME)
        USE HDF5
        CHARACTER(LEN=128), INTENT(IN) :: FILENAME
        INTEGER(HID_T)                 :: FILE_ID_F, FILE_ID
        INTEGER                        :: ERROR
        LOGICAL                        :: FILE_EXISTS

        INQUIRE(FILE = TRIM(FILENAME), EXIST=FILE_EXISTS)
        IF(FILE_EXISTS) THEN
            CALL H5FOPEN_F(FILENAME, H5F_ACC_RDWR_F, FILE_ID, ERROR)
        ELSE
            CALL H5FCREATE_F(FILENAME, H5F_ACC_TRUNC_F, FILE_ID, ERROR)
        END IF
        FILE_ID_F = FILE_ID
    END FUNCTION FILE_ID_F

END MODULE HDF5UTILS
