cmake_minimum_required(VERSION 3.18)
project(test)
set(PROJECT_VERSION "1.0")
project(${PROJECT_NAME} VERSION ${PROJECT_VERSION})
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake_modules)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/fortran/test/cmake_modules)

include( COMPILERCOMMON  )
include( COMPILERFORTRAN )
include( FindLIBS        )
if (APPLE)
    add_compile_options(-fallow-argument-mismatch -cpp)
endif()

include_directories(../libtest/build )
link_directories( ../libtest/build/${CMAKE_BUILD_TYPE} )

function(cleanup)
    unset( F_TEST_SUITE        )
    unset( F_TEST_SUITE CACHE  )
    unset( F_TEST       )
    unset( F_TEST CACHE )
endfunction(cleanup)

option(F_TEST_SUITE "Build single binary with all the tests" OFF)
set(F_TEST "" CACHE STRING "Build single test binary"    )

execute_process(
    COMMAND git rev-parse --abbrev-ref HEAD
    OUTPUT_VARIABLE GIT_BRANCH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# the tests
set( TESTS_LIST_SUITE  "" )
set( TESTS_LIST_SINGLE "" )
list(APPEND TESTS_LIST_SUITE ALGEBRA ALGORITHM HDF5 HDF5UTILS LAPACK MATHUTILS)
list(APPEND TESTS_LIST_SINGLE ${TESTS_LIST_SUITE} EXAMPLE)

if(F_TEST STREQUAL "" AND NOT F_TEST_SUITE)
    message(WARNING "F_TEST and F_TEST_SUITE not are set.\nPlease use \"--build-one SINGLETEST\" "
        "or \"--build-suite\"\nSetting DF_TEST_SUITE=ON")
    set(F_TEST_SUITE ON)
endif()

if((NOT F_TEST STREQUAL "") AND F_TEST_SUITE)
    cleanup()
    message(FATAL_ERROR "Both F_TEST and F_TEST_SUITE are set. CMake will exit...")
endif()

if((NOT F_TEST STREQUAL "") AND (NOT F_TEST IN_LIST TESTS_LIST_SINGLE))
    message("Test ${F_TEST} not found.")
    cleanup()
    message( FATAL_ERROR "CMake will exit...")
endif()

if(NOT F_TEST STREQUAL "")
    include(${F_TEST})
    include_directories(${${TEST_PROJECT_NAME}INCS})
    link_directories(${${TEST_PROJECT_NAME}LINKLIBSDIRS})
    add_executable(${TEST_BIN} ${${TEST_PROJECT_NAME}SRCS})
    target_link_libraries(${TEST_BIN} ${${TEST_PROJECT_NAME}LINKLIBS} debug test_fd optimized test_f)
    if(EXISTS ${CMAKE_SOURCE_DIR}/cmake_modules/${F_TEST}DLL.cmake)
        include(${F_TEST}DLL)
        if(COMMAND ${TEST_PROJECT_NAME}copyDLL)
            cmake_language(CALL ${TEST_PROJECT_NAME}copyDLL)
        endif()
    endif()
else()
    if(F_TEST_SUITE)
    endif(F_TEST_SUITE)
    foreach(TEST_PROJECT_NAME ${TESTS_LIST_SUITE})
       include(${TEST_PROJECT_NAME})
        if(F_TEST_SUITE)
            list(APPEND SUITE_INCS ${${TEST_PROJECT_NAME}INCS})
            list(APPEND SUITE_SRCS ${${TEST_PROJECT_NAME}SRCS})
            list(APPEND SUITE_LINK_DIR ${${TEST_PROJECT_NAME}LINKLIBSDIRS})
            list(APPEND SUITE_LINK ${${TEST_PROJECT_NAME}LINKLIBS})
        else()
          include_directories(${${TEST_PROJECT_NAME}INCS})
            add_executable(${TEST_BIN} ${${TEST_PROJECT_NAME}SRCS} )
            target_link_libraries(${TEST_BIN} ${${TEST_PROJECT_NAME}LINKLIBS} debug test_fd optimized test_f)
            if(EXISTS ${CMAKE_SOURCE_DIR}/cmake_modules/${F_TEST}DLL.cmake)
                include(${F_TEST}DLL)
                if(COMMAND ${TEST_PROJECT_NAME}copyDLL)
                    cmake_language(CALL ${TEST_PROJECT_NAME}copyDLL)
                endif()
            endif()
        endif()
        if(COMMAND ${TEST_PROJECT_NAME}copyDLL)
            cmake_language(CALL ${TEST_PROJECT_NAME}copyDLL)
        endif()
    endforeach()
endif()

if(F_TEST_SUITE)
    add_definitions(-DF_TEST_SUITE )
    include_directories(${SUITE_INCS})
    link_directories(${SUITE_LINK_DIR})
    add_executable(f_suite.test ${SUITE_SRCS} src/suite.f90)
    # target_compile_definitions(f_suite.test PRIVATE SHARED_LIBS_LINK)
    target_link_libraries(f_suite.test PRIVATE ${SUITE_LINK} debug test_fd optimized test_f)
    foreach(TEST_PROJECT_NAME ${TESTS_LIST_SUITE})
        if(EXISTS ${CMAKE_SOURCE_DIR}/cmake_modules/${TEST_PROJECT_NAME}DLL.cmake)
            include(${TEST_PROJECT_NAME}DLL)
            if(COMMAND ${TEST_PROJECT_NAME}copyDLL)
                cmake_language(CALL ${TEST_PROJECT_NAME}copyDLL)
            endif()
        endif()
    endforeach()
endif()

# include(TEST_FDLL)
# if(COMMAND TEST_FcopyDLL)
#    cmake_language(CALL TEST_FcopyDLL)
# endif()

cleanup()
