!/************************/
!/*  algebra.test.F90    */
!/*    VERSION 1.0       */
!/*     2023/03/19       */
!/************************/

MODULE ALGEBRA_TEST
IMPLICIT NONE

PRIVATE :: TEST01
PUBLIC  :: ALGEBRA_TEST_SUITE

CONTAINS

    SUBROUTINE TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        USE ALGEBRA_01
        USE TEST_ROUTINES

        INTEGER, PARAMETER               :: KINDR = KIND(0D0)
        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        REAL(KINDR)                      :: TO_CHECK, RCHECK

        INTEGER                          :: LTOTAL_ERROR, LTOTAL_CHECK
        LOGICAL                          :: LVERBOSE

        REAL(KINDR), DIMENSION(3, 4) :: M1 = RESHAPE( (/ 1, 2, 2, 2,  &
            0, 0, 2, 4, 0, 0, 2, 4 /), (/ 3, 4 /), ORDER = (/ 2, 1 /) )
        REAL(KINDR), DIMENSION(4, 2) :: M2 = RESHAPE( (/ 1, 3, 2, 1,  &
            6, 1, 5, 1 /), (/ 4, 2 /), ORDER = (/ 2, 1 /) )
        REAL(KINDR), DIMENSION(3, 3) :: M3 = RESHAPE( (/ 1, 2, 2, 2,  &
            0, 0, 2, 4, 0 /), (/ 3, 3 /), ORDER = (/ 2, 1 /) )

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0

        CALL RREF(M1)
        TO_CHECK = M1(1,1)
        RCHECK = 1.0E0_KINDR
        CALL CHECK_R8(TO_CHECK, RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        TO_CHECK = M1(1,4)
        RCHECK = -2.0E0_KINDR
        CALL CHECK_R8(TO_CHECK, RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        CALL RREF(M2)
        TO_CHECK = M2(1,1)
        RCHECK = 1.0E0_KINDR
        CALL CHECK_R8(TO_CHECK, RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        TO_CHECK = M2(3,2)
        RCHECK = 0.0E0_KINDR
        CALL CHECK_R8(TO_CHECK, RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        CALL RREF(M3)
        TO_CHECK = M3(1,1)
        RCHECK = 1.0E0_KINDR
        CALL CHECK_R8(TO_CHECK, RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        TO_CHECK = M3(1,2)
        RCHECK = 0.0E0_KINDR
        CALL CHECK_R8(TO_CHECK, RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        TO_CHECK = M3(3,3)
        RCHECK = 1.0E0_KINDR
        CALL CHECK_R8(TO_CHECK, RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        ! PRINT *, "REDUCED ROW ECHELON FORM"
        ! DO I = 1, SIZE(M3,1)
        !    PRINT *, M3(I, :)
        ! END DO

        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "ALGEBRA_TEST01 TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "ALGEBRA_TEST01 TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "ALGEBRA_TEST01 TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
    END SUBROUTINE TEST01


    SUBROUTINE ALGEBRA_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        CALL TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    END SUBROUTINE ALGEBRA_TEST_SUITE

END MODULE ALGEBRA_TEST


#ifndef F_TEST_SUITE
! STANDALONE TEST DEFINITION - USING C PREPROCESSOR
PROGRAM UNITARY_TEST

    USE ALGEBRA_TEST, ONLY : ALGEBRA_TEST_SUITE
    CALL ALGEBRA_TEST_SUITE()

END PROGRAM UNITARY_TEST
#endif
