!/************************/
!/* algorithm.test.F90   */
!/*    VERSION 1.0       */
!/*     2022/09/06       */
!/************************/

MODULE ALGORITHM_TEST
IMPLICIT NONE

PRIVATE :: TEST01, TEST02, TEST03
PRIVATE :: MISSING_INTEGER
PUBLIC  :: ALGORITHM_TEST_SUITE

CONTAINS
    INTEGER FUNCTION MISSING_INTEGER(V)
        USE ALGO_UTILS
        INTEGER, DIMENSION(:), ALLOCATABLE, INTENT(INOUT) :: V
        INTEGER  :: I
        MISSING_INTEGER = 1

        ! CHECK IF THE ARRAY IS ALLOCATED
        IF (.NOT. ALLOCATED(V)) RETURN

        ! ONLY ONE ELEMENT, RETURN CAN BE ONLY 1
        IF(SIZE(V) == 1) RETURN

        CALL QUICKSORT_I4(V,1,SIZE(V))
        ! WRITE(6,'(I10)') V

        DO I=2, SIZE(V)
            IF (V(I) <= 0) CYCLE
            IF (V(I) .EQ. 1) CYCLE
            IF ((V(I) .NE. V(I-1)) .AND. (V(I) .NE. V(I-1) + 1)) EXIT
            MISSING_INTEGER = V(I) + 1
        END DO
    END FUNCTION MISSING_INTEGER


    SUBROUTINE TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        USE ALGO_UTILS
        USE TEST_ROUTINES

        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        INTEGER, PARAMETER               :: KINDR = KIND(0D0)
        INTEGER                          :: V(8), ICHECK

        INTEGER                          :: LTOTAL_ERROR, LTOTAL_CHECK
        LOGICAL                          :: LVERBOSE

        V( 1) =  1; V( 2) =  4; V( 3) = -2; V( 4) =  3
        V( 5) = -1; V( 6) = 11; V( 7) =  0; V( 8) =  1
        CALL QUICKSORT_I4(V,1,8)
        ! WRITE(6,'(I10)') V

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0

        ICHECK = -2
        CALL CHECK_I4(V(1), ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        ICHECK = 0
        CALL CHECK_I4(V(3), ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        ICHECK = 11
        CALL CHECK_I4(V(8), ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST01 TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST01 TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST01 TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
    END SUBROUTINE TEST01


    SUBROUTINE TEST02(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        USE ALGO_UTILS
        USE TEST_ROUTINES

        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        INTEGER, PARAMETER               :: KINDR = KIND(0D0)
        real(KINDR)                      :: V(8), RCHECK

        INTEGER                          :: LTOTAL_ERROR, LTOTAL_CHECK
        LOGICAL                          :: LVERBOSE

        V( 1) =  1.0D0; V( 2) =  1.0D0; V( 3) = -0.11D1; V( 4) =  3.0D0
        V( 5) = -1.0D0; V( 6) = 11.0D0; V( 7) =  1.0D1;  V( 8) =  0.0D0
        CALL QUICKSORT_R8(V,1,8)
        ! WRITE(6,'(F10.5)') V

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0

        RCHECK = -1.1D0
        CALL CHECK_R8(V(1), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        RCHECK = 0.0D0
        CALL CHECK_R8(V(3), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        RCHECK = 1.1D1
        CALL CHECK_R8(V(8), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST02 TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST02 TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST02 TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
    END SUBROUTINE TEST02


    SUBROUTINE TEST03(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        USE TEST_ROUTINES

        INTEGER, INTENT(INOUT), OPTIONAL   :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL   :: VERBOSE
        INTEGER, ALLOCATABLE, DIMENSION(:) :: V
        INTEGER                            :: TO_CHECK, ICHECK

        INTEGER                            :: LTOTAL_ERROR, LTOTAL_CHECK
        LOGICAL                            :: LVERBOSE

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0
        ! EMPTY ARRAY V(1) = 0
        TO_CHECK = MISSING_INTEGER(V)
        ICHECK = 1
        CALL CHECK_I4(TO_CHECK, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        ALLOCATE(V(6))
        V(1) = 1; V(2) = 3; v(3) = 6;
        V(4) = 4; V(5) = 1; v(6) = 2;
        TO_CHECK = MISSING_INTEGER(V)
        ICHECK = 5
        CALL CHECK_I4(TO_CHECK, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        DEALLOCATE(V); ALLOCATE(V(3))
        V(1) = 1; V(2) = 2; v(3) = 3
        TO_CHECK = MISSING_INTEGER(V)
        ICHECK = 4
        CALL CHECK_I4(TO_CHECK, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        DEALLOCATE(V); ALLOCATE(V(2))
        V(1) = -1; V(2) = -3
        TO_CHECK = MISSING_INTEGER(V)
        ICHECK = 1
        CALL CHECK_I4(TO_CHECK, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        DEALLOCATE(V); ALLOCATE(V(4))
        V(1) = -1; V(2) = 2; V(3) = 1; V(4) = 4
        TO_CHECK = MISSING_INTEGER(V)
        ICHECK = 3
        CALL CHECK_I4(TO_CHECK, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST03 TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST03 TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "ALGORITHM_TEST03 TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
        DEALLOCATE(V)
    END SUBROUTINE TEST03


    SUBROUTINE ALGORITHM_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        CALL TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        CALL TEST02(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        CALL TEST03(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    END SUBROUTINE ALGORITHM_TEST_SUITE

END MODULE ALGORITHM_TEST


#ifndef F_TEST_SUITE
! STANDALONE TEST DEFINITION - USING C PREPROCESSOR
PROGRAM UNITARY_TEST

    USE ALGORITHM_TEST, ONLY : ALGORITHM_TEST_SUITE
    CALL ALGORITHM_TEST_SUITE()

END PROGRAM UNITARY_TEST
#endif
