!/************************/
!/*  example.test.F90    */
!/*    VERSION 1.0       */
!/*     2022/10/14       */
!/************************/

MODULE EXAMPLE_TEST
IMPLICIT NONE

PRIVATE :: TEST01
PUBLIC  :: EXAMPLE_TEST_SUITE

CONTAINS
    SUBROUTINE TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)

        USE TEST_ROUTINES

        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE

        INTEGER                          :: LTOTAL_ERROR, LTOTAL_CHECK
        LOGICAL                          :: LVERBOSE

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0

        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "EXAMPLE_TEST TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "EXAMPLE_TEST TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "EXAMPLE_TEST TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
    END SUBROUTINE TEST01


    SUBROUTINE EXAMPLE_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        CALL TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    END SUBROUTINE EXAMPLE_TEST_SUITE

END MODULE EXAMPLE_TEST


#ifndef F_TEST_SUITE
! STANDALONE TEST DEFINITION - USING C PREPROCESSOR
PROGRAM UNITARY_TEST

    USE EXAMPLE_TEST, ONLY : EXAMPLE_TEST_SUITE
    CALL EXAMPLE_TEST_SUITE()

END PROGRAM UNITARY_TEST
#endif
