!/************************/
!/*  hdf5.test.F90       */
!/*    VERSION 1.0       */
!/*     2022/09/06       */
!/************************/

MODULE HDF5_TEST
IMPLICIT NONE

PRIVATE :: TEST01
PUBLIC  :: HDF5_TEST_SUITE

CONTAINS
    SUBROUTINE TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)

        USE HDF5
        USE TEST_ROUTINES

        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        INTEGER, PARAMETER               :: KINDR = KIND(0D0)

        CHARACTER(LEN=128), PARAMETER :: FILENAME =  &
            & './fortran/test/data/mesh01.h5'

        INTEGER(HID_T) :: FILE_ID, DATASET_ID, DATASPACE_ID, DATATYPE_ID

        INTEGER(HSIZE_T), DIMENSION(1:1)            :: DIMS, MAXDIMS
        REAL(KINDR), ALLOCATABLE, DIMENSION(:)      :: BOUNDARIES(:)
        INTEGER(KIND=8), ALLOCATABLE, DIMENSION(:)  :: ELEMENTS(:)
        INTEGER                          :: ERROR, LTOTAL_ERROR, LTOTAL_CHECK
        INTEGER (KIND=8)                 :: I, MESH_TYPE, ELEMENT_TYPE, ICHECK
        REAL (KINDR)                     :: RCHECK
        LOGICAL                          :: LVERBOSE, DSETEQUAL

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0
        I = 1

        CALL H5OPEN_F(ERROR)

        CALL H5FOPEN_F(FILENAME, H5F_ACC_RDONLY_F, FILE_ID, ERROR)
        CALL H5DOPEN_F(FILE_ID, "Mesh/test/MESH_TYPE", DATASET_ID, ERROR)
        DIMS(1:1) = 1
        CALL H5DREAD_F(DATASET_ID, H5T_STD_I64LE, MESH_TYPE, DIMS, ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)

        CALL H5DOPEN_F(FILE_ID, "Mesh/test/ELEMENT_TYPE", DATASET_ID, ERROR)
        CALL H5DREAD_F(DATASET_ID, H5T_STD_I64LE, ELEMENT_TYPE, DIMS, ERROR)
!        WRITE(*,'(A, I0)') "MESH TYPE: ", MESH_TYPE
        ICHECK = 1
        CALL CHECK_I8(MESH_TYPE, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
!        WRITE(*,'(A, I0)') "ELEMENT TYPE: ", ELEMENT_TYPE
        ICHECK = 3
        CALL CHECK_I8(ELEMENT_TYPE, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)

        CALL H5DOPEN_F(FILE_ID, "Mesh/test/boundaries[0]", DATASET_ID, ERROR)
!       CHECK DATATYPE
        CALL H5DGET_TYPE_F(DATASET_ID, DATATYPE_ID, ERROR)
        CALL H5TEQUAL_F(DATATYPE_ID, H5T_NATIVE_DOUBLE, DSETEQUAL, ERROR)
        CALL CHECK_LOGICAL(DSETEQUAL, LTOTAL_CHECK, LTOTAL_ERROR)
!       CHECK CONTENTS
        CALL H5DGET_SPACE_F(DATASET_ID, DATASPACE_ID, ERROR)
        CALL H5SGET_SIMPLE_EXTENT_DIMS_F(DATASPACE_ID, DIMS, MAXDIMS, ERROR)
        ICHECK = 22
        CALL CHECK_I8(DIMS(1), ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        ALLOCATE(BOUNDARIES(1:DIMS(1)))
        CALL H5DREAD_F(DATASET_ID, H5T_NATIVE_DOUBLE, BOUNDARIES, DIMS, ERROR)
        RCHECK = -1.5
        CALL CHECK_R8(BOUNDARIES(13), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        RCHECK = 1.1
        CALL CHECK_R8(BOUNDARIES(14), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)

        CALL H5DOPEN_F(FILE_ID, "Mesh/test/elements", DATASET_ID, ERROR)
        CALL H5DGET_TYPE_F(DATASET_ID, DATATYPE_ID, ERROR)
        CALL H5TEQUAL_F(DATATYPE_ID, H5T_STD_I64LE, DSETEQUAL, ERROR)
        CALL CHECK_LOGICAL(DSETEQUAL, LTOTAL_CHECK, LTOTAL_ERROR)
        CALL H5DGET_SPACE_F(DATASET_ID, DATASPACE_ID, ERROR)
        CALL H5SGET_SIMPLE_EXTENT_DIMS_F(DATASPACE_ID, DIMS, MAXDIMS, ERROR)
        ALLOCATE(ELEMENTS(1:DIMS(1)))
        CALL H5DREAD_F(DATASET_ID, H5T_STD_I64LE, ELEMENTS, DIMS, ERROR)
        ICHECK = 24
        CALL CHECK_I8(DIMS(1), ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        ICHECK = 3
!        CHECK ELEMENT 4 - VERTEX 2
        CALL CHECK_I8(ELEMENTS(15), ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        CALL H5DCLOSE_F(DATASET_ID, ERROR)

        CALL H5FCLOSE_F(FILE_ID, ERROR)
        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "HDF5_TEST TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "HDF5_TEST TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "HDF5_TEST TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
        DEALLOCATE(BOUNDARIES)
        DEALLOCATE(ELEMENTS)
        RETURN
    END SUBROUTINE TEST01


    SUBROUTINE HDF5_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        CALL TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        RETURN
    END SUBROUTINE HDF5_TEST_SUITE

END MODULE HDF5_TEST


#ifndef F_TEST_SUITE
! STANDALONE TEST DEFINITION - USING C PREPROCESSOR
PROGRAM UNITARY_TEST

    USE HDF5_TEST, ONLY : HDF5_TEST_SUITE
    CALL HDF5_TEST_SUITE()

END PROGRAM UNITARY_TEST
#endif
