!/************************/
!/*  hdf5utils.test.F90  */
!/*    VERSION 1.0       */
!/*     2022/09/06       */
!/************************/

MODULE HDF5UTILS_TEST
IMPLICIT NONE

PRIVATE :: TEST01
PUBLIC  :: HDF5UTILS_TEST_SUITE

CONTAINS
    SUBROUTINE TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)

        USE HDF5UTILS
        USE TEST_ROUTINES

        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        INTEGER                          :: LTOTAL_ERROR, LTOTAL_CHECK
        CHARACTER(LEN=128)               :: DATASETNAMEW, DATASETNAMER
        INTEGER, PARAMETER               :: KINDR = KIND(0D0)
        INTEGER                          :: IW, IR, ICHECK
        INTEGER (KIND=8)                 :: I8W, I8R, I8CHECK
        LOGICAL                          :: LVERBOSE
        REAL(KINDR), DIMENSION(2,2)      :: GRIDW
        REAL(KINDR), ALLOCATABLE, DIMENSION(:) :: GRIDR
        REAL (KINDR)                     :: RW, RR, RCHECK

        CHARACTER(LEN=128), PARAMETER :: FILENAME = 'build/test01.h5',   &
     &  GROUPNAME = 'TEST'

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0

        IW = 674
        ICHECK = IW
        DATASETNAMEW = 'INTEGER'
        CALL WRITE_I4(FILENAME, GROUPNAME, DATASETNAMEW, IW)
        DATASETNAMER = 'TEST/INTEGER'
        CALL READ_I4(FILENAME, DATASETNAMER, IR)
        CALL CHECK_I4(IR, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        I8W = 973
        I8CHECK = I8W
        DATASETNAMEW = 'INTEGER_8'
        CALL WRITE_I8(FILENAME, GROUPNAME, DATASETNAMEW, I8W)
        DATASETNAMER = 'TEST/INTEGER_8'
        CALL READ_I8(FILENAME, DATASETNAMER, I8R)
        CALL CHECK_I8(I8R, I8CHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        RW = 9.73
        RCHECK = RW
        DATASETNAMEW = 'REAL'
        CALL WRITE_R8(FILENAME, GROUPNAME, DATASETNAMEW, RW)
        DATASETNAMER = 'TEST/REAL'
        CALL READ_R8(FILENAME, DATASETNAMER, RR)
        CALL CHECK_R8(RR, RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        GRIDW(1,1) = 3.4; GRIDW(1,2) = 2.7;
        GRIDW(2,1) = 4.5; GRIDW(2,2) = 0.9;

        DATASETNAMEW = 'MATRIX'
        CALL WRITE_MR8(FILENAME, GROUPNAME, DATASETNAMEW, GRIDW)
        DATASETNAMER = 'TEST/MATRIX'
        CALL READ_VR8(FILENAME, DATASETNAMER, GRIDR)
        RCHECK = GRIDW(1,1)
        CALL CHECK_R8(GRIDR(1), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        RCHECK = GRIDW(2,2)
        CALL CHECK_R8(GRIDR(4), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "HDF5UTILS_TEST TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "HDF5UTILS_TEST TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "HDF5UTILS_TEST TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
        DEALLOCATE(GRIDR)
    END SUBROUTINE TEST01


    SUBROUTINE HDF5UTILS_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        CALL TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    END SUBROUTINE HDF5UTILS_TEST_SUITE

END MODULE HDF5UTILS_TEST


#ifndef F_TEST_SUITE
! STANDALONE TEST DEFINITION - USING C PREPROCESSOR
PROGRAM UNITARY_TEST

    USE HDF5UTILS_TEST, ONLY : HDF5UTILS_TEST_SUITE
    CALL HDF5UTILS_TEST_SUITE()

END PROGRAM UNITARY_TEST
#endif
