!/************************/
!/*   lapack.test.F90    */
!/*    VERSION 1.0       */
!/*     2022/10/16       */
!/************************/

MODULE LAPACK_TEST
IMPLICIT NONE

PRIVATE :: TEST01, TEST02
PUBLIC  :: LAPACK_TEST_SUITE

CONTAINS
    SUBROUTINE TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        USE MATH_UTILS
        USE TEST_ROUTINES

        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        INTEGER, PARAMETER               :: KINDR = KIND(0D0)
        REAL(KINDR)                      :: A(2,2), B(2), RCHECK
        INTEGER                          :: IPIV(2), INFO

        INTEGER                          :: LTOTAL_ERROR, LTOTAL_CHECK
        LOGICAL                          :: LVERBOSE

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0

        !
        !   SOLVE THE SYSTEM
        !   X + Y = 1
        !   X - Y = 0
        !   => X = Y = 0.5
        !
        A(1,1) = 1.0E0_KINDR; A(1,2) = 1.0E0_KINDR
        A(2,1) = 1.0E0_KINDR; A(2,2) = -1.0E0_KINDR
        B(1)   = 1.0E0_KINDR; B(2)   = 0
        ! SOLVE THE SYSTEM A * X = B
        CALL DGESV(UBOUND(A,1), 1, A, UBOUND(A,1), IPIV, B, UBOUND(A,1), INFO )

        RCHECK = 0.5E0_KINDR
        CALL CHECK_R8(B(1), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)
        CALL CHECK_R8(B(2), RCHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "LAPACK_TEST01 TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "LAPACK_TEST01 TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "LAPACK_TEST01 TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
    END SUBROUTINE TEST01


    SUBROUTINE TEST02(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        USE MATH_UTILS
        USE TEST_ROUTINES

        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        INTEGER                          :: TO_CHECK, ICHECK

        INTEGER                          :: LTOTAL_ERROR, LTOTAL_CHECK
        LOGICAL                          :: LVERBOSE

        IF(PRESENT(VERBOSE)) THEN
            LVERBOSE = VERBOSE
        ELSE
            LVERBOSE = .TRUE.
        ENDIF
        LTOTAL_CHECK = 0
        LTOTAL_ERROR = 0

        CALL TESTMATH_I4(TO_CHECK)
        ICHECK = 1
        CALL CHECK_I4(TO_CHECK, ICHECK, LTOTAL_CHECK, LTOTAL_ERROR)

        IF(.NOT.PRESENT(TOTAL_ERROR) .OR. LVERBOSE) THEN
            WRITE (*, '(A, I0)')  "LAPACK_TEST01 TOTAL NUMBER OF CHECKS: ", &
     &           LTOTAL_CHECK
            WRITE (*, '(A, I0)')  "LAPACK_TEST01 TOTAL NUMBER OF PASSED: ", &
     &           (LTOTAL_CHECK  -  LTOTAL_ERROR)
            WRITE (*, '(A, I0)')  "LAPACK_TEST01 TOTAL NUMBER OF ERRORS: ", &
     &           LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_ERROR)) THEN
            TOTAL_ERROR = TOTAL_ERROR + LTOTAL_ERROR
        ENDIF
        IF(PRESENT(TOTAL_CHECK)) THEN
            TOTAL_CHECK = TOTAL_CHECK + LTOTAL_CHECK
        ENDIF
    END SUBROUTINE TEST02


    SUBROUTINE LAPACK_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        INTEGER, INTENT(INOUT), OPTIONAL :: TOTAL_CHECK, TOTAL_ERROR
        LOGICAL, INTENT(INOUT), OPTIONAL :: VERBOSE
        CALL TEST01(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
        CALL TEST02(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    END SUBROUTINE LAPACK_TEST_SUITE

END MODULE LAPACK_TEST


#ifndef F_TEST_SUITE
! STANDALONE TEST DEFINITION - USING C PREPROCESSOR
PROGRAM UNITARY_TEST

    USE LAPACK_TEST, ONLY : LAPACK_TEST_SUITE
    CALL LAPACK_TEST_SUITE()

END PROGRAM UNITARY_TEST
#endif
