!/************************/
!/*     suite.F90        */
!/*    VERSION 2.0       */
!/*     2022/10/15       */
!/************************/

PROGRAM MAIN

    USE ALGEBRA_TEST,   ONLY : ALGEBRA_TEST_SUITE
    USE ALGORITHM_TEST, ONLY : ALGORITHM_TEST_SUITE
    USE HDF5_TEST,      ONLY : HDF5_TEST_SUITE
    USE HDF5UTILS_TEST, ONLY : HDF5UTILS_TEST_SUITE
    USE LAPACK_TEST,    ONLY : LAPACK_TEST_SUITE
    USE MATHUTILS_TEST, ONLY : MATHUTILS_TEST_SUITE
    IMPLICIT NONE

    INTEGER :: TOTAL_CHECK, TOTAL_ERROR
    LOGICAL :: VERBOSE
    TOTAL_CHECK = 0
    TOTAL_ERROR = 0
    VERBOSE = .TRUE.

    CALL ALGEBRA_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    CALL ALGORITHM_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    CALL HDF5_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    CALL HDF5UTILS_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    CALL LAPACK_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)
    CALL MATHUTILS_TEST_SUITE(TOTAL_CHECK, TOTAL_ERROR, VERBOSE)

    WRITE (*, '(A, I0)')  "TOTAL NUMBER OF CHECKS: ", &
        &           TOTAL_CHECK
    WRITE (*, '(A, I0)')  "TOTAL NUMBER OF PASSED: ", &
        &           (TOTAL_CHECK  -  TOTAL_ERROR)
    WRITE (*, '(A, I0)')  "TOTAL NUMBER OF ERRORS: ", &
        &           TOTAL_ERROR

END PROGRAM MAIN
