cmake_minimum_required(VERSION 3.18)
project(test)
set(PROJECT_VERSION "1.0")
project(${PROJECT_NAME} VERSION ${PROJECT_VERSION})
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake_modules)
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cpp/test/cmake_modules)

include( COMPILERCOMMON )
include( COMPILERCPP    )
include( FindLIBS       )
if(MSVC)
    set(CMAKE_CXX_STANDARD 20  )
else()
    set(CMAKE_CXX_STANDARD 17  )
endif()

generic_libs_find(doctest ON  )
include_directories( ${DOCTEST_INCLUDE_DIRS}/doctest )

function(cleanup)
    unset( CPP_TEST_SUITE        )
    unset( CPP_TEST_SUITE CACHE  )
    unset( CPP_TEST       )
    unset( CPP_TEST CACHE )
endfunction(cleanup)

option(CPP_TEST_SUITE "Build single binary with all the tests" OFF)
set(CPP_TEST "" CACHE STRING "Build single test binary"    )

# the tests
set( TESTS_LIST_SUITE  "" )
set( TESTS_LIST_SINGLE "" )
list(APPEND TESTS_LIST_SUITE COUT LOGGING MATRIX SOLVERS)
list(APPEND TESTS_LIST_SINGLE ${TESTS_LIST_SUITE} BLAS EXAMPLE LAPACK LOGGING_RELEASE)

if(CPP_TEST STREQUAL "" AND NOT CPP_TEST_SUITE)
    message(WARNING "CPP_TEST and CPP_TEST_SUITE not are set.\nPlease use \"--build-one SINGLETEST\" "
        "or \"--build-suite\"\nSetting DCPP_TEST_SUITE=ON")
    set(CPP_TEST_SUITE ON)
endif()

if((NOT CPP_TEST STREQUAL "") AND CPP_TEST_SUITE)
    cleanup()
    message(FATAL_ERROR "Both CPP_TEST and CPP_TEST_SUITE are set. CMake will exit...")
endif()

if((NOT CPP_TEST STREQUAL "") AND (NOT CPP_TEST IN_LIST TESTS_LIST_SINGLE))
    message("Test ${CPP_TEST} not found.")
    cleanup()
    message( FATAL_ERROR "CMake will exit...")
endif()

if(NOT CPP_TEST STREQUAL "")
    include(${CPP_TEST})
    include_directories(${${TEST_PROJECT_NAME}INCS})
    link_directories(${${TEST_PROJECT_NAME}LINKLIBSDIRS})
    add_executable(${TEST_BIN} ${${TEST_PROJECT_NAME}SRCS} src/main.cpp)
    # target_compile_definitions(${TEST_BIN} PRIVATE SHARED_LIBS_LINK)
    target_link_libraries(${TEST_BIN} ${${TEST_PROJECT_NAME}LINKLIBS} )
    if(EXISTS ${CMAKE_SOURCE_DIR}/cmake_modules/${CPP_TEST}DLL.cmake)
        include(${CPP_TEST}DLL)
        if(COMMAND ${TEST_PROJECT_NAME}copyDLL)
            cmake_language(CALL ${TEST_PROJECT_NAME}copyDLL)
        endif()
    endif()
else()
    if(CPP_TEST_SUITE)
        # Define logging, COUT and COUTM
        add_definitions( -DLOGGING -DCOUTEXT )
    endif(CPP_TEST_SUITE)
    foreach(TEST_PROJECT_NAME ${TESTS_LIST_SUITE})
        include(${TEST_PROJECT_NAME})
        if(CPP_TEST_SUITE)
            list(APPEND SUITE_INCS ${${TEST_PROJECT_NAME}INCS})
            list(APPEND SUITE_SRCS ${${TEST_PROJECT_NAME}SRCS})
            list(APPEND SUITE_LINK_DIR ${${TEST_PROJECT_NAME}LINKLIBSDIRS})
            list(APPEND SUITE_LINK ${${TEST_PROJECT_NAME}LINKLIBS})
        else()
            include_directories(${${TEST_PROJECT_NAME}INCS})
            add_executable(${TEST_BIN} ${${TEST_PROJECT_NAME}SRCS})
            # target_compile_definitions(${TEST_BIN} PRIVATE SHARED_LIBS_LINK)
            target_link_libraries(${TEST_BIN} ${${TEST_PROJECT_NAME}LINKLIBS})
            if(EXISTS ${CMAKE_SOURCE_DIR}/cmake_modules/${CPP_TEST}DLL.cmake)
                include(${CPP_TEST}DLL)
                if(COMMAND ${TEST_PROJECT_NAME}copyDLL)
                    cmake_language(CALL ${TEST_PROJECT_NAME}copyDLL)
                endif()
            endif()
        endif()
        if(COMMAND ${TEST_PROJECT_NAME}copyDLL)
            cmake_language(CALL ${TEST_PROJECT_NAME}copyDLL)
        endif()
    endforeach()
endif()

if(CPP_TEST_SUITE)
    include_directories(${SUITE_INCS})
    link_directories(${SUITE_LINK_DIR})
    add_executable(cpp_suite.test ${SUITE_SRCS} src/main.cpp)
    # target_compile_definitions(cpp_suite.test PRIVATE SHARED_LIBS_LINK)
    target_link_libraries(cpp_suite.test PRIVATE ${SUITE_LINK})
    foreach(TEST_PROJECT_NAME ${TESTS_LIST_SUITE})
        if(EXISTS ${CMAKE_SOURCE_DIR}/cmake_modules/${TEST_PROJECT_NAME}DLL.cmake)
            include(${TEST_PROJECT_NAME}DLL)
            if(COMMAND ${TEST_PROJECT_NAME}copyDLL)
                cmake_language(CALL ${TEST_PROJECT_NAME}copyDLL)
            endif()
        endif()
    endforeach()
endif()

cleanup()
